### PR TITLE
added video download function

### PR DESCRIPTION
**Pull request by Zebraslive**
you can generate a download url for the original file using the dwnload($url) function
Google Photos converts videos from the bottom up. 360p to 1080p. 
Added conditions to the getPhotoGoogle() function else if($count >= 0) 
It will return the download url when no resolutions have been converted yet. this can be streamed the same way but you can't use range requests with it.

### CODE REVIEW

**Comment by Zebraslive** [comment]
fixed error
- Undefined variable: $files 

added error handling for when no resolutions are returned.
```
if (isset($data[1])) {
      $url = explode('%3Dm', $data[1]);  
        $decode = urldecode($url[0]);
    } else {
        $decode = "";
    }
```

**Comment by Zebraslive** [comment]
@ArdiArtani

**Comment by khalisafkari** [comment]
@Zebraslive can you see the project that I wrote with the node https://github.com/khalisafkari/google-photos-etc

**Comment by Zebraslive** [comment]
@khalisafkari looks good. I'll test it out when I get some free time.

**Pull request merged**
