### PR TITLE
Basic VideoJS Embed

### PR DESCRIPTION
**Pull request by Zebraslive**
Created basic embed that doesn't use encryption on source. It uses videoJS instead of jwplayer and has resolution switcher plugin.
http://mizi.ml/embedp.php?id=https://photos.google.com/share/AF1QipMTEPAiVF8t0YqLukflnOSQjwfd8ARIoT2h37AXvYO1uaWodbeiFoBUDuD_19tEbg/photo/AF1QipPA2Bq0JlAR9LoGD3mogsxSb9OZWEG4XqBDD4Rv?key=cjhUT0xrZjM5NGN2SVRLOVptZU5SMUlKV0lQYWpB

### CODE REVIEW

**Comment by khalisafkari** [comment]
Not work http://demo.filedeo.stream/photos/?id=https://photos.google.com/share/AF1QipMkdSWn7sOqwhmWANTAS6V_yVl5wWMVlS3cGILCrUNGiZKqBOxzewUDRjaziw1wiQ/photo/AF1QipP3y-6ywFafXVRGxpAxv_2q_UPnqz1s7n2R5SUN?key=cmM1T2VvM1dPOFdQYzVSRTN4UFBLYVZWdW0xOVJB

**Comment by Zebraslive** [comment]
@khalisafkari what? it works fine. why post that link here? this pull request hasn't been approved so it's not going to work with the main branch this> http://mizi.ml/embedp.php?id=https://photos.google.com/share/AF1QipMTEPAiVF8t0YqLukflnOSQjwfd8ARIoT2h37AXvYO1uaWodbeiFoBUDuD_19tEbg/photo/AF1QipPA2Bq0JlAR9LoGD3mogsxSb9OZWEG4XqBDD4Rv?key=cjhUT0xrZjM5NGN2SVRLOVptZU5SMUlKV0lQYWpB is for using with iframes.

**Comment by khalisafkari** [comment]
Show with json url

**Comment by Zebraslive** [comment]
@khalisafkari http://mizi.ml/drive/?url=https://photos.google.com/share/AF1QipMTEPAiVF8t0YqLukflnOSQjwfd8ARIoT2h37AXvYO1uaWodbeiFoBUDuD_19tEbg/photo/AF1QipPA2Bq0JlAR9LoGD3mogsxSb9OZWEG4XqBDD4Rv?key=cjhUT0xrZjM5NGN2SVRLOVptZU5SMUlKV0lQYWpB

**Comment by Zebraslive** [comment]
@ArdiArtani Please approve or close this pull when you get some free time.
Thanks!

**Comment by khalisafkari** [comment]
@Zebraslive @ArdiArtani Please tutorial grab to download https://videp-downloads.googleusercontent.com

**Comment by khalisafkari** [comment]
@Zebraslive @ArdiArtani please add fiture grab https://video-downloads-googleusercontent.com available in videos on google photos

**Comment by Zebraslive** [comment]
@khalisafkari Ok I think I can do that.

**Comment by Zebraslive** [comment]
@khalisafkari I haven't added this to my branch yet but I will be adding caching system at some point.
```php
function directlink($url) {
$internalErrors = libxml_use_internal_errors(true);
$file = file_get_contents($url);
$dom = new DOMDocument();
@$dom->loadHTML($file);
$count = 0;
$ss = "";
$zd = "";
foreach($dom->getElementsByTagName('script') as $js) {
if ($count === 13 || $count > 14) {
$ss .= $js->nodeValue;
}
$count++;
}
$zd = explode(',"', $ss);
$zd = explode('"', $zd[2]);
return $zd[0]; //final video-downloads.googleusercontent.com url	
}
```

**Comment by Love656** [comment]
It was not found v1080p and v720p and v360p 
i need grab download link to src="download link"
Until the video is processed

**Comment by Love656** [comment]
Did you understand the idea?

**Pull request closed without merging**
